### PR TITLE
fix(#49): Fixed Recursive Downloads

### LINKED ISSUE #49: Unable to Download Recursive Files
(Hi! 👋  Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

## What are the steps to reproduce this issue?
1. Have existing files on device under one or more sub directories (i.e `/ROOT/subdir/file.py`)
2. Attempt to download files from device
3. Only files located under `/ROOT` download, while any under a sub dir report as failed.

## What happens?
* Any files not placed directly in the root directory fail to download
* The reported path in terminal is mangled as so:
```sh

# Actual Path: /stubs/esp32_1_10_0/gc.py
[18/66] Reading stubsesp32_1_10_0/gc.py
Failed to download stubsesp32_1_10_0/gc.py
```
* Pymakr hangs when attempting to create any missing directories on the host to match the tree on the MCU

## What were you expecting to happen?
* Any missing directories should be created on host
* Any files under sub directories on the MCU should have downloaded

## Any logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
* N\A

## Any other comments?
* In [shell-workers.py (Line 69)](https://github.com/pycom/pymakr-vsc/blob/7717026641ad005698f9beafa81130633b62835c/src/board/shell-workers.js#L69) roughly 200 empty bytes such as this: `\0x00` were populating the list of supposed files, therefore all going through the callback.

## What versions of software are you using?

**Operating system:**
* Linux 5.0.9-arch1-1-vfio x86_64 GNU/Linux (Manjaro)

**VSCode version:**
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.9-arch1-1-vfio
```

**Pymakr version:**
* 1.1.2

### PR DESCRIPTION
**Pull request by BradenM**
(Hi! 👋 Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

## What does this implement/fix? Explain your changes.
* Fixes downloading files under any sub directories on the MCU
* Fixes failure to create missing directories on the host

## Does this close any currently open issues?
* Closes #49 

## Any relevant logs, error output, etc?
*(If it’s long, please paste to https://gist.github.com and insert the link here)*
* N/A

## Any other comments?
* Also fixes comment in #49 regarding empty bytes being processed as files

## Where has this been tested?

**Operating system:**
* Linux 5.0.9-arch1-1-vfio x86_64 GNU/Linux (Manjaro)

**VSCode version:**
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.9-arch1-1-vfio
```

**Pymakr version:**
* 1.1.2

### CODE REVIEW

File: src/helpers/utils.js [hunk 1]
```diff
@@ -97,20 +97,22 @@ export default class Utils {
...
+    return this.ensureDirectoryExistence(dirname)
   }
 
 
   ensureDirectoryExistence(dirname) {
-    console.log(dirname)
-    if (fs.existsSync(dirname)) {
-      return true
+    if (!fs.existsSync(dirname)) {
+      this.mkDirRecursive(dirname)
```
Comment (BradenM) [inline src/helpers/utils.js]: If you happened to want to bump up the minimum Node version to 10 ;) we could just do this 
```suggestion
      fs.mkdirSync(dirname, { recursive: true})
```

which would also make `mkDirRecursive` unnecessary

Comment (RalphHogenbirk) [reply src/helpers/utils.js]: Will check at some point if that's realistic :) If so, we'll do that, cause that recursive param looks way nicer

**Comment by RalphHogenbirk** [comment]
Very nicely done sir! Tested and working
